# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MasterServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MasterServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12MasterServer.proto\"\x15\n\x06numero\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x18\n\x05input\x12\x0f\n\x07\x66itxers\x18\x01 \x01(\t\"\x1c\n\x08resultat\x12\x10\n\x08resultat\x18\x01 \x01(\t\"\x07\n\x05\x65mpty2\xca\x01\n\x0cMasterServer\x12$\n\rGetResultatCW\x12\x06.input\x1a\t.resultat\"\x00\x12$\n\rGetResultatWC\x12\x06.input\x1a\t.resultat\"\x00\x12$\n\x0c\x43reateWorker\x12\x07.numero\x1a\t.resultat\"\x00\x12$\n\x0c\x44\x65leteWorker\x12\x07.numero\x1a\t.resultat\"\x00\x12\"\n\x0bListWorkers\x12\x06.empty\x1a\t.resultat\"\x00\x62\x06proto3'
)




_NUMERO = _descriptor.Descriptor(
  name='numero',
  full_name='numero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='numero.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=43,
)


_INPUT = _descriptor.Descriptor(
  name='input',
  full_name='input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fitxers', full_name='input.fitxers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=69,
)


_RESULTAT = _descriptor.Descriptor(
  name='resultat',
  full_name='resultat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultat', full_name='resultat.resultat', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=99,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['numero'] = _NUMERO
DESCRIPTOR.message_types_by_name['input'] = _INPUT
DESCRIPTOR.message_types_by_name['resultat'] = _RESULTAT
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

numero = _reflection.GeneratedProtocolMessageType('numero', (_message.Message,), {
  'DESCRIPTOR' : _NUMERO,
  '__module__' : 'MasterServer_pb2'
  # @@protoc_insertion_point(class_scope:numero)
  })
_sym_db.RegisterMessage(numero)

input = _reflection.GeneratedProtocolMessageType('input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'MasterServer_pb2'
  # @@protoc_insertion_point(class_scope:input)
  })
_sym_db.RegisterMessage(input)

resultat = _reflection.GeneratedProtocolMessageType('resultat', (_message.Message,), {
  'DESCRIPTOR' : _RESULTAT,
  '__module__' : 'MasterServer_pb2'
  # @@protoc_insertion_point(class_scope:resultat)
  })
_sym_db.RegisterMessage(resultat)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'MasterServer_pb2'
  # @@protoc_insertion_point(class_scope:empty)
  })
_sym_db.RegisterMessage(empty)



_MASTERSERVER = _descriptor.ServiceDescriptor(
  name='MasterServer',
  full_name='MasterServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=111,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetResultatCW',
    full_name='MasterServer.GetResultatCW',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_RESULTAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetResultatWC',
    full_name='MasterServer.GetResultatWC',
    index=1,
    containing_service=None,
    input_type=_INPUT,
    output_type=_RESULTAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateWorker',
    full_name='MasterServer.CreateWorker',
    index=2,
    containing_service=None,
    input_type=_NUMERO,
    output_type=_RESULTAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteWorker',
    full_name='MasterServer.DeleteWorker',
    index=3,
    containing_service=None,
    input_type=_NUMERO,
    output_type=_RESULTAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListWorkers',
    full_name='MasterServer.ListWorkers',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESULTAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVER)

DESCRIPTOR.services_by_name['MasterServer'] = _MASTERSERVER

# @@protoc_insertion_point(module_scope)
